services:
  postgres:
    image: postgres:16
    container_name: platform-launchpad-postgres
    environment:
      POSTGRES_USER: platform_user
      POSTGRES_PASSWORD: platform_pass
      POSTGRES_DB: platform_launchpad
    ports:
      - "5432:5432"
    volumes:
      - platform_postgres_data:/var/lib/postgresql/data

volumes:
  platform_postgres_data:
