"""create initial application schema

Revision ID: 752fd6a84fcb
Revises: 
Create Date: 2026-07-14 06:40:14.948250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '752fd6a84fcb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('role', sa.String(length=20), server_default=sa.text("'user'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_valid_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('environment_type', sa.String(length=20), nullable=False),
    sa.Column('application_version', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('external_url', sa.String(length=2048), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('destroyed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("environment_type IN ('development', 'staging', 'demo')", name=op.f('ck_environments_valid_environment_type')),
    sa.CheckConstraint("status IN ('pending', 'provisioning', 'active', 'failed', 'destroying', 'destroyed')", name=op.f('ck_environments_valid_status')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_environments_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments'))
    )
    op.create_index(op.f('ix_environments_environment_type'), 'environments', ['environment_type'], unique=False)
    op.create_index(op.f('ix_environments_owner_id'), 'environments', ['owner_id'], unique=False)
    op.create_index('ix_environments_owner_id_name', 'environments', ['owner_id', 'name'], unique=False)
    op.create_index('ix_environments_owner_id_status', 'environments', ['owner_id', 'status'], unique=False)
    op.create_index(op.f('ix_environments_status'), 'environments', ['status'], unique=False)
    op.create_table('deployment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('requested_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation IN ('provision', 'destroy', 'retry', 'upgrade')", name=op.f('ck_deployment_requests_valid_operation')),
    sa.CheckConstraint("status IN ('queued', 'processing', 'succeeded', 'failed', 'cancelled')", name=op.f('ck_deployment_requests_valid_status')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_deployment_requests_nonnegative_attempt_count')),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_deployment_requests_environment_id_environments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_deployment_requests_requested_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployment_requests'))
    )
    op.create_index(op.f('ix_deployment_requests_environment_id'), 'deployment_requests', ['environment_id'], unique=False)
    op.create_index('ix_deployment_requests_environment_id_status', 'deployment_requests', ['environment_id', 'status'], unique=False)
    op.create_index(op.f('ix_deployment_requests_operation'), 'deployment_requests', ['operation'], unique=False)
    op.create_index(op.f('ix_deployment_requests_requested_at'), 'deployment_requests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_deployment_requests_requested_by_id'), 'deployment_requests', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_deployment_requests_status'), 'deployment_requests', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('deployment_request_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('result', sa.String(length=20), server_default=sa.text("'success'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("result IN ('success', 'failure', 'denied')", name=op.f('ck_audit_logs_valid_result')),
    sa.ForeignKeyConstraint(['deployment_request_id'], ['deployment_requests.id'], name=op.f('fk_audit_logs_deployment_request_id_deployment_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_audit_logs_environment_id_environments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_deployment_request_id'), 'audit_logs', ['deployment_request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_environment_id'), 'audit_logs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_result'), 'audit_logs', ['result'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_result'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_environment_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_deployment_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_deployment_requests_status'), table_name='deployment_requests')
    op.drop_index(op.f('ix_deployment_requests_requested_by_id'), table_name='deployment_requests')
    op.drop_index(op.f('ix_deployment_requests_requested_at'), table_name='deployment_requests')
    op.drop_index(op.f('ix_deployment_requests_operation'), table_name='deployment_requests')
    op.drop_index('ix_deployment_requests_environment_id_status', table_name='deployment_requests')
    op.drop_index(op.f('ix_deployment_requests_environment_id'), table_name='deployment_requests')
    op.drop_table('deployment_requests')
    op.drop_index(op.f('ix_environments_status'), table_name='environments')
    op.drop_index('ix_environments_owner_id_status', table_name='environments')
    op.drop_index('ix_environments_owner_id_name', table_name='environments')
    op.drop_index(op.f('ix_environments_owner_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_environment_type'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
