"""add unique owner environment name constraint

Revision ID: 7a7bca3dd54f
Revises: 752fd6a84fcb
Create Date: 2026-07-25 06:26:21.764757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7bca3dd54f'
down_revision: Union[str, Sequence[str], None] = '752fd6a84fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_environments_owner_id_name', 'environments', ['owner_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_environments_owner_id_name', 'environments', type_='unique')
    # ### end Alembic commands ###
